import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import { AuditLogger } from './lib/AuditLogger';

/**
 * Triggers when a new intake form is submitted.
 * Parses the form answers against the template's risk triggers.
 */
export const onIntakeFormSubmitted = functions.firestore
  .document('studios/{studioId}/intake_submissions/{submissionId}')
  .onCreate(async (snap, context) => {
    const data = snap.data();
    const { studioId, submissionId } = context.params;
    
    const templateId = data.templateId;
    const templateDoc = await admin.firestore().doc(`studios/${studioId}/intake_templates/${templateId}`).get();
    
    if (!templateDoc.exists) {
      console.error('Template not found for submission', submissionId);
      return null;
    }
    
    const template = templateDoc.data()!;
    const fields = template.fields || [];
    const submittedData = data.data || {};
    
    let isFlagged = false;

    // Evaluate Risk Triggers
    for (const field of fields) {
      if (field.riskTriggers && submittedData[field.id] !== undefined) {
        const answer = submittedData[field.id];
        
        for (const trigger of field.riskTriggers) {
          // Simplistic matching: if answer matches the trigger condition exactly
          if (answer === trigger.condition || (Array.isArray(answer) && answer.includes(trigger.condition))) {
            
            // Create a Risk Flag
            await admin.firestore().collection(`studios/${studioId}/risk_flags`).add({
              clientId: data.clientId,
              type: 'medical_condition', // defaulting for now, could be derived
              severity: trigger.severity,
              description: trigger.flagDescription,
              createdAt: admin.firestore.FieldValue.serverTimestamp(),
              createdBy: 'system' // Auto-generated by Compliance Engine
            });
            
            isFlagged = true;
          }
        }
      }
    }

    // Update Client Status if flagged
    if (isFlagged) {
      await admin.firestore().doc(`studios/${studioId}/clients/${data.clientId}`).update({
        status: 'flagged',
        updatedAt: admin.firestore.FieldValue.serverTimestamp()
      });
      
      await AuditLogger.logEvent(studioId, 'CLIENT_FLAGGED', {
        clientId: data.clientId,
        submissionId: submissionId,
        reason: 'Intake form risk triggers activated'
      });
    }

    return null;
  });

/**
 * Triggers when a new consent is signed.
 * Simulates generating a PDF and attaching the URL to the document.
 */
export const onConsentCreated = functions.firestore
  .document('studios/{studioId}/consents/{consentId}')
  .onCreate(async (snap, context) => {
    const { studioId, consentId } = context.params;
    const data = snap.data();

    // In a real app, we would use pdfkit or puppeteer here,
    // upload to Firebase Storage, and get the download URL.
    const mockPdfUrl = `https://storage.podea.app/${studioId}/consents/${consentId}.pdf`;

    await snap.ref.update({
      pdfUrl: mockPdfUrl,
      updatedAt: admin.firestore.FieldValue.serverTimestamp()
    });

    await AuditLogger.logEvent(studioId, 'CONSENT_PDF_GENERATED', {
      clientId: data.clientId,
      consentId: consentId
    });

    return null;
  });

/**
 * Callable function for a practitioner to review an intake form.
 */
export const reviewIntakeForm = functions.https.onCall(async (data, context) => {
  if (!context.auth) throw new functions.https.HttpsError('unauthenticated', 'Not logged in');
  
  const { studioId, submissionId, notes } = data;
  const callerClaims = context.auth.token;

  if (callerClaims.studioId !== studioId) {
    throw new functions.https.HttpsError('permission-denied', 'Wrong studio');
  }

  // Allow practitioner, studio_admin, platform_admin
  if (!['practitioner', 'studio_admin', 'platform_admin'].includes(callerClaims.role)) {
    throw new functions.https.HttpsError('permission-denied', 'Only practitioners can review');
  }

  await admin.firestore().doc(`studios/${studioId}/intake_submissions/${submissionId}`).update({
    practitionerReviewed: true,
    practitionerId: context.auth.uid,
    reviewNotes: notes || '',
    updatedAt: admin.firestore.FieldValue.serverTimestamp()
  });

  await AuditLogger.logEvent(studioId, 'INTAKE_REVIEWED', {
    submissionId,
    practitionerId: context.auth.uid
  });

  return { success: true };
});
